// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvDjakfY63_-hDWVjlOkCdnWJxeSP2EnU',
    appId: '1:148516695964:web:5a63202cd5af6f4bb36259',
    messagingSenderId: '148516695964',
    projectId: 'appproject-c6429',
    authDomain: 'appproject-c6429.firebaseapp.com',
    storageBucket: 'appproject-c6429.appspot.com',
    measurementId: 'G-DSXY5EDCLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDxyuBZyPWoolmNsqlumIuE-4zKLaP41c',
    appId: '1:148516695964:android:4e0d3907cbdf5144b36259',
    messagingSenderId: '148516695964',
    projectId: 'appproject-c6429',
    storageBucket: 'appproject-c6429.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw-NHgYCAeCdy7jzb618X2VWflMDkT2Wg',
    appId: '1:148516695964:ios:53e1557ac0981f7eb36259',
    messagingSenderId: '148516695964',
    projectId: 'appproject-c6429',
    storageBucket: 'appproject-c6429.appspot.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw-NHgYCAeCdy7jzb618X2VWflMDkT2Wg',
    appId: '1:148516695964:ios:53e1557ac0981f7eb36259',
    messagingSenderId: '148516695964',
    projectId: 'appproject-c6429',
    storageBucket: 'appproject-c6429.appspot.com',
    iosBundleId: 'com.example.appProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvDjakfY63_-hDWVjlOkCdnWJxeSP2EnU',
    appId: '1:148516695964:web:db6ee76b3088cf76b36259',
    messagingSenderId: '148516695964',
    projectId: 'appproject-c6429',
    authDomain: 'appproject-c6429.firebaseapp.com',
    storageBucket: 'appproject-c6429.appspot.com',
    measurementId: 'G-FEVWJJFQ00',
  );
}
